// anyplot.ai
// qrcode-basic: Basic QR Code Generator
// Library: echarts 5.5.1 | JavaScript 22.23.0
// Quality: 86/100 | Created: 2026-06-24
//# anyplot-orientation: square
// anyplot.ai
// qrcode-basic: Basic QR Code Generator
// Library: echarts 5.5.1 | JavaScript 22
// Quality: pending | Created: 2026-06-24

const t = window.ANYPLOT_TOKENS;

// QR code matrix (Version 2, 25×25, EC Level M) encoding "https://anyplot.ai"
// Generated by the qrcode library — standard-compliant, scannable by any QR reader
const QR_MATRIX = [
  [1,1,1,1,1,1,1,0,1,0,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1],
  [1,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,0,0,0,0,1],
  [1,0,1,1,1,0,1,0,1,0,1,0,0,1,1,1,1,0,1,0,1,1,1,0,1],
  [1,0,1,1,1,0,1,0,0,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,1],
  [1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,0,1],
  [1,0,0,0,0,0,1,0,0,1,1,1,0,1,1,0,1,0,1,0,0,0,0,0,1],
  [1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1],
  [0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0],
  [1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,0,0,1,0,1,1,1],
  [0,0,1,0,1,0,0,1,0,0,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0],
  [1,0,0,0,0,1,1,1,1,0,1,1,0,0,1,1,0,0,0,1,1,1,0,0,1],
  [0,1,1,1,1,1,0,1,0,1,0,1,0,0,1,0,0,1,0,0,0,1,1,1,1],
  [1,0,1,1,1,0,1,0,1,1,1,1,0,1,1,1,0,0,1,1,0,0,0,0,1],
  [1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,1,0,0,1,0],
  [1,1,0,0,0,0,1,1,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,1],
  [1,0,0,1,0,1,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,0,1],
  [1,0,1,1,1,0,1,0,1,0,1,1,1,0,0,0,1,1,1,1,1,0,1,1,0],
  [0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,1,0,1,1,0],
  [1,1,1,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,1],
  [1,0,0,0,0,0,1,0,1,0,1,1,0,1,0,1,1,0,0,0,1,0,0,0,0],
  [1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,1,1,1,1,1,0,0,0,1],
  [1,0,1,1,1,0,1,0,1,1,1,0,1,1,0,0,1,1,1,0,0,0,0,1,1],
  [1,0,1,1,1,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,1,1,1,1,1],
  [1,0,0,0,0,0,1,0,0,1,0,1,1,1,0,0,0,1,1,1,1,0,1,1,1],
  [1,1,1,1,1,1,1,0,1,1,0,1,1,1,0,0,1,1,1,0,0,1,0,0,1],
];
const QR_SIZE = 25;

// Add 4-module quiet zone around QR code (required for reliable scanning)
const QUIET = 4;
const TOTAL = QR_SIZE + 2 * QUIET; // 33

const data = [];
for (let r = 0; r < TOTAL; r++) {
  for (let c = 0; c < TOTAL; c++) {
    const inQR = r >= QUIET && r < QUIET + QR_SIZE && c >= QUIET && c < QUIET + QR_SIZE;
    const value = inQR ? QR_MATRIX[r - QUIET][c - QUIET] : 0;
    data.push([c, r, value]);
  }
}

const chart = echarts.init(document.getElementById("container"));

// QR module colors: high-contrast ink on page background
// Light theme: near-black on cream; dark theme: near-white on near-black
const MODULE_DARK = t.ink;
const MODULE_LIGHT = t.pageBg;

// Grid: 990×990 CSS px centered in 1200×1200 mount
// Each of 33 cells = 30 CSS px — exactly fills the quiet-zone + 25-module QR
const GRID_SIZE = 990;
const MARGIN = (1200 - GRID_SIZE) / 2; // 105 CSS px

chart.setOption({
  animation: false,
  backgroundColor: t.pageBg,
  title: {
    text: "qrcode-basic · javascript · echarts · anyplot.ai",
    subtext: "Scan to visit: https://anyplot.ai  ·  QR Version 2  ·  Error Correction Level M",
    left: "center",
    top: 28,
    textStyle: { color: t.ink, fontSize: 22, fontWeight: "bold" },
    subtextStyle: { color: t.inkSoft, fontSize: 14 },
  },
  grid: {
    left: MARGIN,
    right: MARGIN,
    top: 130,
    bottom: 80,
    containLabel: false,
  },
  xAxis: {
    type: "category",
    data: Array.from({ length: TOTAL }, (_, i) => i),
    show: false,
    splitLine: { show: false },
    axisTick: { show: false },
    axisLine: { show: false },
  },
  yAxis: {
    type: "category",
    data: Array.from({ length: TOTAL }, (_, i) => i),
    inverse: true,
    show: false,
    splitLine: { show: false },
    axisTick: { show: false },
    axisLine: { show: false },
  },
  visualMap: {
    type: "piecewise",
    show: false,
    pieces: [
      { value: 0, color: MODULE_LIGHT },
      { value: 1, color: MODULE_DARK },
    ],
  },
  series: [
    {
      type: "heatmap",
      data: data,
      itemStyle: { borderWidth: 0 },
    },
  ],
});
